### ISSUE TITLE
autoload problem

### ISSUE THREAD

**Issue by SilverEngineTeam** [lotfio/aven#1]
PHP Warning:  require(../autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\silver\aven\aven on line 10

Warning: require(../autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\silver\aven\aven on line 10
PHP Fatal error:  require(): Failed opening required '../autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\silver\aven\aven on line 10

Fatal error: require(): Failed opening required '../autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\silver\aven\aven on line 10

**Comment by lotfio** [comment]
as stated in the documentation [**here**](https://github.com/lotfio/aven#aven-console-cli-) You need to include the right files.
