### ISSUE TITLE
Collection routing missing

### ISSUE THREAD

**Issue by Nejcc** [lotfio/aven#4]
We need to add  Route::crud()  or Route::collection()    that contain  reserved methods: 
Create, Update, Store, index, get, all, delete inside the controller

Look up for those methods or give error if something is missing by options to set  via route ->allow(['change',...]);  

Route::crud('/news', 'NewsController')->grant('change'); 
or 
Route::crud('/news', 'NewsController')->grant(['change', 'middlewear:index']); 

Allow /Grantmethod execute command  to something pass 
- We can same time make another helper chain method  deny

**Comment by lotfio** [comment]
coming soon in version 0.4
